-- retrieve all columns from the customer table
select * 
from customer;

-- Display only film_id, title, and rating from the film table.
select film_id, title, rating
from film;

-- Retrieve the first 15 records from the actor table.
select *
from actor
limit 15;

-- Retrieve all customers and sort them by last_name in ascending order.
select *
from customer
order by last_name; 

--Display payment_id, customer_id, and amount, sorted by amount from lowest to highest.
select payment_id, customer_id, amount
from payment
order by amount;

-- Retrieve customers sorted by:
    -- first_name in ascending order
    -- last_name in descending order
select first_name, last_name
from customer
order by first_name;

select first_name, last_name
from customer
order by last_name desc;

-- Retrieve all payments where the amount is greater than 5.
select amount
from payment
where amount > 5;

-- Retrieve all payments where the amount is between 3.99 and 6.99.
select amount
from payment
where amount between 3.99 and 6.99;

--Retrieve all customers whose first_name starts with the letter J.
select first_name
from customer
where first_name like 'J%';

-- Retrieve all films where the description contains the word “Action”.
select title, description
from film
where description like 'action';

--Retrieve payments greater than 7, sorted by amount in descending order.
select amount
from payment
where amount > 7
order by amount desc;

-- Retrieve customers whose first name ends with “n”, sorted alphabetically.
select first_name
from customer
where first_name like '%n'
order by first_name;

-- Calculate the total amount spent by each customer.
select sum(amount), customer_id
from payment
group by customer_id;

-- Retrieve the average payment amount per customer.
select avg(amount), customer_id
from payment
group by customer_id;

-- Calculate the total revenue generated by each staff member.
select sum(amount), staff_id
from payment
group by staff_id;

--Identify the top 5 customers based on total payment amount.
select sum(amount), customer_id
from payment
group by customer_id
order by sum(amount) desc
limit 5;

-- Find the average film length per release year.
select title, avg(length), release_year
from film
group by release_year, title;

--Retrieve the highest single payment amount in the payment table.
select amount
from payment
order by amount desc
limit(1);

--Count how many payments each customer has made.
select amount, customer_id
from payment
order by amount desc;

--Retrieve customers who are active and sort them by first_name.
select first_name, last_name, active
from customer
where active = '1'
order by first_name;

select * 
from customer 
where first_name ilike 'j%'
order by last_name desc;
--offset 6

--Count how many payments each customer has made.
select customer_id,
COUNT(customer_id) as mem
from payment
group by customer_id
having COUNT(customer_id) > 39
order by mem desc;

select * 
from customer;

select * 
from payment;

-- names of top 10 highest spenders
select customer.customer_id, customer.first_name, customer.last_name, sum(payment.amount)
from customer
inner join payment
on customer.customer_id = payment.customer_id
group by customer.customer_id, customer.first_name, customer.last_name
order by sum(payment.amount) desc
limit (10);

-- names of top 10 highest spenders
select cust.customer_id, cust.first_name, cust.last_name, sum(pay.amount) as totamount
from customer as cust
inner join payment as pay
on cust.customer_id = pay.customer_id
group by cust.customer_id, cust.first_name, cust.last_name
order by totamount desc
limit (10);

select cust.customer_id, cust.first_name, cust.last_name, pay.amount, pay.customer_id
from customer as cust
full join payment as pay
on cust.customer_id = pay.customer_id;
--group by cust.customer_id, cust.first_name, cust.last_name
--order by totamount desc
--limit (10);

--select * from customer